#
# docker-compose.yml — определяет сервисы для разработки и тестирования.

# Что нужно сделать:
#   - Настроить сервисы для:
#       - PostgreSQL (или MySQL) с начальной базой.
#       - Приложения Spring Boot (если нужно).
#   - Открыть нужные порты (например, 5432, 8080).
#   - Настроить volume для хранения данных БД.
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    restart: unless-stopped
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  .postgres-data:
